version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    depends_on: [fpm]
    restart: always
    ports:
      - 86:80
    volumes:
      - ./public:/var/www/html/public
    logging:
      options:
        max-size: "20m"
        max-file: "1"
  fpm:
    build:
      context: .
      dockerfile: ./docker/fpm.dockerfile
      target: prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    restart: always
    volumes:
      - ./api/storage:/var/www/html/storage
      - ./api/public/files:/var/www/html/public/files
    logging:
      options:
        max-size: "20m"
        max-file: "1"
  mysql:
    image: mysql:8.0
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'hozaika'
      MYSQL_USER: 'hozaika'
      MYSQL_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mysql-volume:/var/lib/mysql
