version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    depends_on: [fpm]
    restart: always
    ports:
      - 82:80
    volumes:
      - ./public:/var/www/html/public
    logging:
      options:
        max-size: "20m"
        max-file: "1"
    networks:
      - api_stage
  fpm:
    build:
      context: .
      dockerfile: ./docker/fpm.dockerfile
      target: prod
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/var/www/html # dev
    logging:
      options:
        max-size: "20m"
        max-file: "1"
    networks:
      - api_stage
  mysql:
    image: mysql:8.0
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    networks:
      - api_stage
    volumes:
      - mysql-volume:/var/lib/mysql
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - api_stage
    volumes:
      - redis-volume:/data
networks:
  api_stage:
    driver: bridge
volumes:
  mysql-volume:
  redis-volume:
